### ISSUE TITLE
The examples in the document aren't really examples

### ISSUE THREAD

**Issue by jimsch** [spasm-wg/smime#7]
This is an open errata from from 5751 by Peter Guttman.  The examples in the document are not real S/MIME examples but are not labeled as being fakes.

We should define which way we want to go with this issue.

**Comment by seanturner** [comment]
People often code from examples so I'm all for making the examples included in the draft real-world examples.  This is also makes me wonder whether we should add new examples to https://datatracker.ietf.org/doc/rfc4134/ that show authEnvelopedData.

**Comment by jimsch** [comment]
This is now done in the WGLC draft
